### PR TITLE
Update subdomains.json

### PR DESCRIPTION
**Pull request by MaskDuck**
**Subdomain requested:**  maskduck.runs-on.tech

**CNAME record:** maskduck.ninja

[**Preview/working URL of website**](https://maskduck.ninja)

### CODE REVIEW

**Comment by aakhilv** [comment]
I have added your request to the DNS records, once you have finished setting it up on your end, I will close and merge this PR.

**Comment by MaskDuck** [comment]
Done?

**Comment by aakhilv** [comment]
https://maskduck.runs-on.tech leads to a 404 GitHub page.

**Comment by MaskDuck** [comment]
Seems a bit weird, which DNS record should I add to?

**Comment by aakhilv** [comment]
> Seems a bit weird, which DNS record should I add to?

I wouldn't know. Look up the instructions on setting up a custom domain for your hosting provider.

**Pull request closed without merging**
