### PR TITLE
abhay.runs-on.tech

### PR DESCRIPTION
**Pull request by EpicGamer007**
**Subdomain requested:** abhay.runs-on.tech

**CNAME record:** 26ece53e-5ca7-40d2-a7ad-cc13eb22808d.id.repl.co

**Preview/working URL of website:** https://abhay7.is-a.dev (Temporary, will redirect to abhay.runs-on.tech when this gets approved)

Thanks :)

### CODE REVIEW

**Comment by aakhilv** [comment]
I have added your subdomain to the Cloudflare DNS records, once you have finished setting it up on your end, please let me know.

**Comment by EpicGamer007** [comment]
Done :)

**Comment by aakhilv** [comment]
Great! Merging and closing the PR now. 👍

**Comment by EpicGamer007** [comment]
Thanks a lot!

**Comment by EpicGamer007** [comment]
@aakhilv , hey, I was trying out my site with the subdomain and it appears that none of my javascript is running. When I open up the console, I first see this:
image
I see this weird string in the type area that I definitely did not add myself. This obviously means something is injecting code into   my site. 

Then I scroll down and see this, which I 100% did not add:
image
It appears that this is what is causing the weird javascript type changes, but having a cloudflare script randomly lying around basically cancelling my js (I use CSP and it blocks js from the url the cloudflare script has), and I do not want any cloudflare scripts on my site. 

I also explored some other sites in the `subdomains.json` file and all of them have the same `rocket-loader.min.js` file which leads me to believe it is none other than cloudflare injecting this. Your README also said "special thanks to cloudflare" which further solidifies my point.

If you can, can you please remove this script from running? Or if possible, on a per site basis?

Thanks.

**Comment by aakhilv** [comment]
Ah I see what you mean, I have disabled the feature now. Let me know if the problem has been fixed.

**Comment by EpicGamer007** [comment]
Yup :), works like a charm

**Pull request merged**
