### PR TITLE
prozt.runs-on.tech

### PR DESCRIPTION
**Pull request by Techpro709**
**Subdomain requested: prozt (prozt.runs-on.tech)**

**CNAME record: nginx-production.up.railway.app**
 
**Preview/working URL of website: I do not know if this is it because I needed the CNAME so I put in the domain so it may not work but here https://1b5c6d621142.up.railway.app/**

### CODE REVIEW

**Comment by aakhilv** [comment]
Okay, I have added the DNS records, let me know if it is working once the setup on your end has finished.

**Comment by Techpro709** [comment]
It says I got redirected too many times 

https://prozt.runs-on.tech



**This page isn’t working prozt.runs-on.tech redirected you too many times.**
**Try clearing your cookies.**
**ERR_TOO_MANY_REDIRECTS**

**Comment by Techpro709** [comment]
Oh Also I found this in the docs
https://docs.railway.app/deploy/exposing-your-app#lets-encrypt-ssl-certificates

It has the exact same error

Maybe you need to do whatever this is?

**Comment by aakhilv** [comment]
Thanks for letting me know about that! I have now fixed the problem, and it appears to be working. 👍

**Pull request merged**
